### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Technius** [Technius/simpl#4]
TODO list (in no particular order):
* [x] External functions
* [ ] (#7) Parametric polymorphism
* [ ] Support for builtin functions
  * [ ] sin, cos, tan
  * [ ] string length
* [ ] String operations
  * [ ] Concatenate binary operator
  * [ ] to string (for any type)
  * [ ] string interpolation (syntax sugar)
* [ ] Lambdas/inline functions
* [ ] Partial application
* [ ] Known-size immutable arrays
* [ ] Mangle names in LLVM output (e.g. `fun foo` becomes `@simpl.foo`)
* [ ] Multiple compilation units
  * [ ] Multiple source file input
  * [ ] Fully qualified names
* [ ] Expression location diagnostics (e.g. line numbers)
  * [x] Annotations
  * [ ] Source positions in messages
* [x] (#5) ANF intermediate representation with explicit join points (like from Compiling without Continuations)
* Static analysis and optimizations
  * [ ] Referential transparency (limited)
  * [ ] Reachability and dead code elimination
  * [ ] Constant propagation
